#include "/etc/bind/named.conf.options";
include "/etc/bind/named.conf.local";
include "/etc/bind/named.conf.default-zones";

acl internal {
   192.168.98.0/24;
   172.16.0.0/24;
   172.16.1.0/24;
   172.16.100.0/24;
   172.16.110.0/24;
   172.16.120.0/24;
   10.0.0.0/24;
};

options {
    directory "/var/cache/bind";
    forwarders {
        172.16.100.2;
        1.1.1.1;
    };
    allow-query { internal; };
};

zone "mgnt.msrls.net" IN {
    type master;
    file "/app/dns/zones/mgnt.msrls.net.zone";
};

zone "infra.msrls.net" IN {
    type master;
    file "/app/dns/zones/infra.msrls.net.zone";
};

zone "internal.msrls.net" IN {
    type master;
    file "/app/dns/zones/internal.msrls.net.zone";
};

zone "dev.msrls.net" IN {
    type master;
    file "/app/dns/zones/dev.msrls.net.zone";
};

zone "monitor.msrls.net" IN {
    type master;
    file "/app/dns/zones/monitor.msrls.net.zone";
};

zone "app.msrls.net" IN {
    type master;
    file "/app/dns/zones/app.msrls.net.zone";
};

