version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 10010:3000
    restart: unless-stopped
    volumes:
      - ./config/custom.ini:/etc/grafana/grafana.ini
      - ./data/var:/var/lib/grafana
      - ./data/logs:/var/log/grafana
      - ./data/plugins:/var/lib/grafana/plugins
      - ./data/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana	
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_LOG_LEVEL=debug
    user: "999"
networks: {}
