version: "3"
services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    hostname: planka
    volumes:
      - ./data/user-avatars:/app/public/user-avatars
      - ./data/project-background-images:/app/public/project-background-images
      - ./data/attachments:/app/private/attachments
    ports:
      - 3001:1337
    environment:
      - BASE_URL=https://board.dev.msrls.net
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=${SECRET_KEY}
      - TRUST_PROXY=1
      - DEFAULT_ADMIN_EMAIL=admin@msrls.net # Do not remove if you want to prevent this user from being edited/deleted
      - DEFAULT_ADMIN_PASSWORD=Admin015
      - DEFAULT_ADMIN_NAME=Misty Admin
      - DEFAULT_ADMIN_USERNAME=mistyadm
      - SHOW_DETAILED_AUTH_ERRORS=true # Set to true to show more detailed authentication error messages. It should not be enabled without a rate limiter for security reasons.

      # - ALLOW_ALL_TO_CREATE_PROJECTS=true

      # - OIDC_ISSUER=https://keycloak.auth.msrls.net/realms/msrls-apps
      # - OIDC_CLIENT_ID=planka
      # - OIDC_CLIENT_SECRET=jtMRAKP8bptuVv4ibYWHFJhggv8FWpgs
      # - OIDC_ID_TOKEN_SIGNED_RESPONSE_ALG=https://keycloak.auth.msrls.net/realms/msrls-apps/protocol/openid-connect/token
      # - OIDC_USERINFO_SIGNED_RESPONSE_ALG=https://keycloak.auth.msrls.net/realms/msrls-apps/protocol/openid-connect/userinfo
      # - OIDC_SCOPES=openid profile email
      # - OIDC_RESPONSE_MODE=fragment
      # - OIDC_USE_DEFAULT_RESPONSE_MODE=true
      # - OIDC_ADMIN_ROLES=admin
      # - OIDC_CLAIMS_SOURCE=userinfo
      # - OIDC_EMAIL_ATTRIBUTE=email
      # - OIDC_NAME_ATTRIBUTE=name
      # - OIDC_USERNAME_ATTRIBUTE=preferred_username
      # - OIDC_ROLES_ATTRIBUTE=groups
      # - OIDC_IGNORE_USERNAME=true
      # - OIDC_IGNORE_ROLES=true
      # - OIDC_ENFORCED=true

      # Email Notifications (https://nodemailer.com/smtp/)
      # - SMTP_HOST=
      # - SMTP_PORT=587
      # - SMTP_NAME=
      # - SMTP_SECURE=true
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_FROM="Demo Demo" <demo@demo.demo>
      # - SMTP_TLS_REJECT_UNAUTHORIZED=false

      # Optional fields: accessToken, events, excludedEvents
      # - |
      #   WEBHOOKS=[{
      #     "url": "http://localhost:3001",
      #     "accessToken": "notaccesstoken",
      #     "events": ["cardCreate", "cardUpdate", "cardDelete"],
      #     "excludedEvents": ["notificationCreate", "notificationUpdate"]
      #   }]

      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=
      # - GOOGLE_CHAT_WEBHOOK_URL=
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    hostname: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d planka
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  user-avatars: null
  project-background-images: null
  attachments: null
  db-data: null
networks: {}
