server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name home.app.msrls.net;

        location / {
                proxy_pass http://dockge-ctl.sys.msrls.net:3000;
        }
}