name: Homepage CI/CD
run-name: ${{ gitea.actor }} Homepage Automation 🚀
on: [push]

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v4
     - name: create ssh folder
       run: mkdir -p ~/.ssh
     - name: setup ssh key
       run: echo "${{ secrets.GITKEY }}" > ~/.ssh/id_rsa
     - name: setup ssh key permissions
       run: chmod 600 ~/.ssh/id_rsa
     - name: copy compose file to server
       run: scp -o StrictHostKeyChecking=no compose.yaml autopilot@dockge-dev-node01.mgnt.msrls.net:/apps/homepage
     - name: copy environment file to server
       run: scp -o StrictHostKeyChecking=no .env autopilot@dockge-dev-node01.mgnt.msrls.net:/apps/homepage
     - name: copy configuration files to server
       run: scp -ro StrictHostKeyChecking=no data/* autopilot@dockge-dev-node01.mgnt.msrls.net:/apps/homepage/data
     - name: spin up the container
       run: ssh -o StrictHostKeyChecking=no autopilot@dockge-dev-node01.mgnt.msrls.net "cd /apps/homepage && sudo docker compose up -d"
     - run: echo "This job's status is ${{ job.status }}."
