name: Uptime-Kuma CI/CD
run-name: ${{ gitea.actor }} Uptime-Kuma Automation 🚀
on: [push]

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v4
     - name: create ssh folder
       run: mkdir -p ~/.ssh
     - name: setup ssh key
       run: echo "${{ secrets.GITKEY }}" > ~/.ssh/id_rsa
     - name: setup ssh key permissions
       run: chmod 600 ~/.ssh/id_rsa
     - name: copy compose file to server
       run: scp -o StrictHostKeyChecking=no compose.yaml autopilot@dockge-dev-node02.mgnt.msrls.net:/apps/uptime-kuma
     - name: spin up the container
       run: ssh -o StrictHostKeyChecking=no autopilot@dockge-dev-node02.mgnt.msrls.net "cd /apps/uptime-kuma && sudo docker compose up -d"
     - run: echo "This job's status is ${{ job.status }}."
     